Create Fake-Data for frontend
D3nnis249/GenialTanken-Capstone pull request #10
Opened 2022-04-27 14:27 UTC by D3nnis249

Hey, thank you for your review

- App.css, is deleted, you can see it in the other PR.
- App.jsx, Here, provisionally, the first page was built to show the functionality of the list. In the course of the application different pages will be created and the data revised
- GasSation.jsx, Will reflect the functionality of each card in the next steps

Here, our first site.
![Bildschirmfoto 2022-04-27 um 16 26 23](https://user-images.githubusercontent.com/100355993/165541536-825c5bdf-af56-41f0-a9bd-7a9bb08a89f1.png)

2022-04-27 21:11 UTC, mpagels requested changes
Hey Dennis, hey Alex.

Very good work here. I like that you've kept the pull request small. I also like that you provides a small pull request description that gave me some information about the changes you both made.

Here is my feedback:
The name of the pull request is a bit misleading. I was expecting some backend code with the title `create database` ;-) The title naming could be more leading.

I have mentioned it in the review itself. Code or components that have no impact, should not be included in a pull request. The `GasStation` component is not implemented. This is a `bad practice`

I also found some issues that need to be resolved. Pls review.

2022-04-27 21:11 UTC, mpagels commented on client/src/App.css
> +.Ulist{
What is an `Ulist`. Try to find meaningful names for your classes that indicate clearly where and what it represents.
Maybe this could be named `GasStationList` or `StationList`?

2022-04-27 21:11 UTC, mpagels commented on client/src/App.jsx
> +  console.log(data);
You have a lonely `console.log`. You don't want a console.log in your production code.

2022-04-27 21:11 UTC, mpagels commented on client/src/App.jsx
> +          <li className="ListItems" key={station.uuid}>
Good job thinking of the `key` prop and using the `uuid` of the `station object` 👍

2022-04-27 21:11 UTC, mpagels commented on client/src/App.css
> +.ListItems {
I would recommend naming the class in singular. And a meaningful name would be better.

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +export default GasStation;
I know you wrote, that this component is used later, but still, this `component` is not used in your app. So it should not be in this `pull request`.

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +//   }, []);
Commented code here. If the code is not used, you should delete it. 
You need it maybe later? Thank god you have `git` and your code `version controlled`. Travel back in time and get your code snippet back, if needed. IF! ;-)

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +    <>
You don't need the `fragement` here (`<>...</>`). Your code is at the end returning` jsx` with just one parent.
```html
<li onClick={handleDetails}>
  <h2>{name}</h2>
</li>
```
or 
```html
<li onClick={handleDetails}>
  <h2>{name}</h2>
  <h2>{e5}</h2>
</li>
```

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +          <h2>{e5}</h2>
This is `semantically` incorrect. You should use `headlines` in `descending` order. After a `h2` should come a `h3`.
Read more about it [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes)  
Maybe the content is not a `headline` after all?

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +      )}
You could refactor this to:

```suggestion
        <li onClick={handleDetails}>
          <h2>{name}</h2>
          {gasStationDetailsOn && <h2>{e5}</h2>}
        </li>
```
and save some lines of code.

The two `h2`s are still not correct semantically speaking.

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +  const [gasStation, setGasStation] = useState({});
What is this state doing?

2022-04-27 21:11 UTC, mpagels commented on client/src/components/GasStation.jsx
> +  const [gasStationDetailsOn, setGasStationDetailsOn] = useState(true);
A good naming for a `variable` that holds a `boolean` starts with `is` or `has`.
For example
- `isOpen` indicates, something is open or not (`true` or `false`) 
- `hasLikes` indicates, something has likes (`true` or `false`) 

And I think I don't need the wording `gasStation` in `gasStationsDetailsOn`. I'm in the `GasStation` components. Something like `isDetailOpen` is enough. I know, that this should have something to do with my `GasStation`

2022-04-27 21:15 UTC, mpagels commented
Oh, and I just realized. What about `tests`? 😬 You could test, if the station is rendered.

2022-04-28 10:11 UTC, merged

2022-04-28 13:06 UTC, D3nnis249 commented on client/src/components/GasStation.jsx
> +  const [gasStationDetailsOn, setGasStationDetailsOn] = useState(true);
thank you this is helpful